server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feiju?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: a1151342179
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

